#!/bin/sh
# ToyamasOS live-build configuration recipe
# Target OS: Debian 13 (Trixie) Minimal x86_64

lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --parent-mirror-bootstrap "http://deb.debian.org/debian/" \
    --parent-mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --debian-installer false \
    --binary-images iso-hybrid \
    --bootloader grub-efi \
    --compression squashfs \
    --iso-application "ToyamasOS Minimal Server" \
    --iso-publisher "ToyamasOS Team <https://github.com/Wildanel321/ToyamasOS>" \
    --iso-volume "TOYAMASOS_1_0" \
    "${@}"

# Inject debootstrap options directly to the config file to bypass command-line parsing bugs in live-build
echo 'LB_DEBOOTSTRAP_OPTIONS="--include=coreutils,usr-is-merged,systemd --no-check-gpg"' >> config/bootstrap
