version: '3.8'

services:
  laravel-app:
    image: bitnami/laravel:10
    container_name: toyamas-laravel-app
    restart: always
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DB_HOST=laravel-db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - laravel-db

  laravel-db:
    image: mariadb:10.11
    container_name: toyamas-laravel-db
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
